### ISSUE TITLE
Bug with Webpack 5

### ISSUE THREAD

**Issue by svperfecta** [mentos1386/webpack-glsl-loader#10]
Hi there - There seems to be a bug in the latest version of the package. I'm using it with Webpack 5.

```
ERROR in ./src/components/models/torus/torus.vs
Module build failed (from ./node_modules/ts-shader-loader/lib/index.js):
Error: Cannot find module 'fs/promises'
Require stack:
-/node_modules/ts-shader-loader/lib/index.js
- /node_modules/loader-runner/lib/loadLoader.js
- /node_modules/loader-runner/lib/LoaderRunner.js
- /node_modules/webpack/lib/NormalModuleFactory.js
```

I haven't looked into the error to far yet, but reverting to 1.0.6 fixes it, though NPM Audit notes that there is a security issue with a dependency.

This is potentially related [webpack/webpack-cli/issues/1612]

**Comment by mentos1386** [comment]
Hm interesting. What version od Nodejs are you using?

The "fs/promises" was added in v14[1]. Make sure you are using at least that or newer.

[1] https://nodejs.org/api/fs.html#promises-api
