### ISSUE TITLE
#include throwing error

### ISSUE THREAD

**Issue by n3rdw1z4rd** [mentos1386/webpack-glsl-loader#14]
Hello,

First, thanks for the wonderful package!

I have an include statement at the beginning of a shader file, but when the bundle is loaded in the browser, I am getting the following error:

`ERROR: 0:32: 'include' : invalid directive name`

The line in the shader looks like this:
`#include "./common.glsl";`

the shader file `common.glsl` is located in the same folder as the importing shader file.

What am I doing wrong?

I am using three.js

Thanks,
John

**Comment by mentos1386** [comment]
Hey John, are you using the latest (2.0.2) version? I think this should be fixed with #12.

**Comment by n3rdw1z4rd** [comment]
Hi mentos1386, yes, I am using 2.0.2: `"ts-shader-loader": "^2.0.2",`

I think it may be a `three.js` issue, but I have not confirmed this.
