### ISSUE TITLE
Is this supposed to work with Typescript?

### ISSUE THREAD

**Issue by nuthinking** [mentos1386/webpack-glsl-loader#2]
If it's a JS to import the shader works fine. But if it's a typescript file I get `Cannot find module './shader.glsl' or its corresponding type declarations.ts(2307)`

**Comment by lynxnot** [comment]
@nuthinking it should work by adding a `glsl.d.ts` to your project with the following content:

```ts
declare module '*.glsl' {
  const value: string;
  export default value;
}
```
You can check my boilerplate project [here](https://github.com/lynxnot/ts-regl-webpack-starter)
HIH

**Comment by mmontag** [comment]
A bit magical, but it works...

**Comment by mentos1386** [comment]
I have improved the README (mentioning the need for `glsl.d.ts`) and added @lynxnot boilerplate as an example (in example folder).

**Comment by tribaaldos** [comment]
This helped me to fix mine , i had the project with Vite. 

https://medium.com/@jarekmyjak/how-to-use-glsl-shader-files-with-typescript-c1d50fc72244
