### ISSUE TITLE
 conflict with WebGL-GLSL-Editor

### ISSUE THREAD

**Issue by crafted-composites** [mentos1386/webpack-glsl-loader#3]
https://github.com/racz16/WebGL-GLSL-Editor/issues/16

when using WebGL-GLSL-Editor VSCode extension and "ts-shader-loader" in line import statement "@import ./file;" all variables declared above the @ statement are greyed out and receive "variable is never used"

your es6 implementation is the best of the shader loaders and would be great to see it work with the GLSL extension

<img width="434" alt="Screen Shot 2022-01-20 at 11 19 06 PM" src="https://user-images.githubusercontent.com/80181237/150484698-c8e3edda-3120-4d7c-a409-156a038fdc26.png">

**Comment by crafted-composites** [comment]
commenting out the @import statement fixs the problem while still functioning,

**Comment by mentos1386** [comment]
@crafted-composites it's probably due to `@import` being a custom syntax not official glsl syntax. Which makes the glsl editor extension behave weird.

**Comment by mentos1386** [comment]
Closing as solution is to do comment out the import/include statement.
